from snakemake.utils import min_version
min_version("9.0")

# configfile path is interpreted relative to the working directory
# not relative to the location of the snakefile that contains the statement.
configfile: "config/config.yaml"
report: "report/workflow.rst"


include: "rules/athena_dev.smk"
include: "rules/traccc.smk"
include: "rules/tracking.smk"
include: "rules/triton.smk"
include: "rules/test.smk"

SAMPLES = config["samples"]
GNNCHAINS = config["gnn_chains"]
rule all:
    input:
        expand("workarea/trackingCTD2025/{dataset}/idpvm.{chain}.primary.triton.main.tracking.{dataset}.root", dataset=SAMPLES, chain=GNNCHAINS)
