from snakemake.utils import min_version
min_version("9.0")

configfile: "config/config.yaml"
report: "report/workflow.rst"


include: "rules/athena_dev.smk"
include: "rules/traccc.smk"
include: "rules/tracking.smk"
include: "rules/triton.smk"
include: "rules/test.smk"

SAMPLES = ["MuonPU0", "HaaPU0", "HaaPU200"]
rule all:
    input:
        "workarea/tracking/ttbar/aod.gnn4itkMLLocal.ttbar.root"
        # "workarea/tracking/ttbar/aod.ckf.ttbar.root"
